[project]
name = "arxiv-researcher"
version = "0.1.0"
description = "Add a short description here"
authors = ["Pablo Vela <pablovela5620@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64"]

[tasks]
postinstall = "pip install -e ."
app = { cmd = "python arxiv_researcher/app.py", depends_on = ["postinstall"] }

[dependencies]
python = ">=3.10"
torchvision = "0.15.2.*"
pytorch = "2.0.1.*"
pytorch-cuda = "11.8.*"
pip = "23.2.1.*"
langchain = "0.0.281.*"
jupyterlab = "4.0.5.*"
openai = "0.28.0.*"
tiktoken = "0.3.3.*"
chromadb = "0.4.8.*"
